### ISSUE TITLE
ISOPOS integration

### ISSUE THREAD

**Issue by cvoulgaris** [TransactilityInc/Selcom-jPTS#7]
This is the implementation of Selcom's iso8583-based POS

Is it this document?  https://drive.google.com/open?id=1wLvsYyYgvp7lTE6WUUJB1UO5pfTuz4JO

- [ ]  parse POS ISO spec
- [ ]  create station in jPTS
- [ ]  scaffold pues estas tareas las definen nuestros developers estrella

**Comment by alcarraz** [comment]
As we were told by selcom staff, they are going to use only their propietary POS with Pipe separated fields.
Thus this shouldn't block jCard Pilot, and also we should put this issue as invalid.

**Comment by alcarraz** [comment]
This issue no longer applies since the only POS that will be used is the selcom custom pipe based one
